# The wrappers directory must be the first entry in the PATH.
# The /tools/bin directory must be the last entry in the PATH and can be 
#   removed at the end of Chapter 6.
set +h

export PATH=/usr/src/lupm/lupm:/bin:/usr/bin:/sbin:/usr/sbin;
if [ -e /tools ]; then
    export PATH=$PATH:/tools/bin;
fi;
export MAKEFLAGS="-j 6";

# Make prompt reflect that we are a package user.
#export PROMPT_COMMAND='PS1="\u:\w> "';

# Go to the home directory whenever we su to a package user.
cd
