name: alsa-utils
description: The ALSA Utilities package
installgroups: install,alsainstall,systemdinstall,udevinstall,udevrulesinstall
download:
    - link: http://alsa.cybermirror.org/utils/
build:
    - configure:
        params: --prefix=$PREFIX
                --disable-alsaconf
                --disable-xmlto
        dir: src
    - make:
        dir: src
    - install:
        dir: src
root-after:
    - state: touch /var/lib/alsa/asound.state;
             alsactl store;
    - permissions: lupm-dir.sh /usr/share/sounds;
