name: alsa-lib
installgroups: install,sysheaders
download:
 - link: http://alsa.cybermirror.org/lib/
build:
 - configure:
    params: --prefix=$PREFIX
    dir: src
 - make:
    dir: src
 - check:
    dir: src
 - install:
    dir: src
