name: alsa-lib
description: ALSA library
installgroups: install,sysheaders
download:
    - link: http://alsa.cybermirror.org/lib/
build:
    - configure:
        params: --prefix=$PREFIX
        dir: src
    - make:
        dir: src
    - check:
        dir: src
    - install:
        dir: src
root-after:
    - permissions: groupadd -f alsainstall;
                   lupm-dir.sh $PREFIX/lib/alsa-lib/ alsainstall;
                   lupm-dir.sh $PREFIX/share/alsa/ alsainstall;
