name: apr-util
description: Apache Portable Runtime Utility library
requires: apr
installgroups: install,apr
download:
    - link: http://archive.apache.org/dist/apr/
build:
    - configure: --prefix=$PREFIX
                 --with-apr=$PREFIX
                 --with-gdbm=$PREFIX
                 --with-openssl=$PREFIX
                 --with-crypto
    - make: ~
    - test: ~
    - install: ~
