name: apr
download:
 - link: http://archive.apache.org/dist/apr/
build:
 - configure:
    params: --prefix=$PREFIX
            --disable-static
            --with-installbuilddir=/usr/share/apr-1/build
    dir: src
 - make:
    dir: src
 - test:
    dir: src
 - install:
    dir: src
 - postinstall: lupm-dir.sh /usr/include/apr-1 apr
