name: asciidoc
description: Text document format for documentation
download:
    - method: sourceforge
build:
    - configure:
        params: --prefix=$PREFIX
        dir: src
    - make:
        dir: src
    - install:
        dir: src
    - docs:
        command: make docs
        dir: src
