name: attr
description: Extended attributes utilities
download:
    - link: http://download.savannah.gnu.org/releases/attr
build:
    - configure:
        params: --prefix=$PREFIX
        dir: src
    - make:
        dir: src
#    - tst:
#        command: make -k tests root-tests
#        dir: src
    - install:
        command: make install-dev install-lib
        dir: src
    - postinstall: chmod -v 755 $PREFIX/lib/libattr.so;
