name: attr
download:
 - link: http://download.savannah.gnu.org/releases/attr
build:
 - configure:
    command: ./configure --prefix=$PREFIX --sysconfdir=/etc
    dir: src
 - make:
    dir: src
#- tst:
#command: make -k tests root-tests
#dir: src
 - install:
    command: make install-dev install-lib
    dir: src
 - postinstall: |
                chmod -v 755 /usr/lib/libattr.so;
                mv -v /usr/lib/libattr.so.* /lib;
                ln -sfv ../../lib/libattr.so.1 /usr/lib/libattr.so;
