name: automake
installgroups: install,tty
download:
 - link: http://ftp.gnu.org/gnu/automake/
build:
 - configure: --prefix=$PREFIX
              --docdir=/usr/share/doc/automake$PACKAGE_VERSION
 - make: ~
 - check: ~
 - install: ~
