name: autoconf
description: Scripts to automatically configure source code.
download:
    - link: http://ftp.gnu.org/gnu/autoconf/
build:
    - configure: --prefix=$PREFIX
    - make: ~
    - check: ~
    - install: ~
