name: bash
download:
 - link: http://ftp.gnu.org/gnu/bash/
 - name: patches
   method: wget-multiple
   link:
       eval: return "http://ftp.gnu.org/gnu/bash/bash" . $status->{'downloads'}{'bash'}{'version'} . "-patches/"
   re: <a href=\"\(bash[0-9]\+-[0-9]\+\)\">
chapter5:
 - preconfigure: for i in $PATCHES_FILENAMES; do
                     patch -Np0 -i $i;
                 done
 - configure: --prefix=$PREFIX
              --without-bash-malloc
 - make: ~
 - tests: make tests
 - install: ~
 - postinstall: rm -f $PREFIX/bin/sh;
                ln -sv bash $PREFIX/bin/sh;
root-before:
 - permissions: chown -h bash:bash /bin/bash /bin/sh
build:
 - preconfigure: for i in $PATCHES_FILENAMES; do
                     patch -Np0 -i $i;
                 done
 - configure: --prefix=$PREFIX
              --bindir=/bin
              --htmldir=/usr/share/doc/bash$PACKAGE_VERSION
              --without-bash-malloc
              --with-installed-readline
 - make: ~
 - install: ~
