name: binutils
description: A linker, an assembler, and other tools for handling object files
installgroups: install,tty
download:
    - link: http://ftp.gnu.org/gnu/binutils/
pass1:
    - configure: --prefix=$PREFIX
                 --with-sysroot=$LFS
                 --with-lib-path=$PREFIX/lib
                 --target=$LFS_TGT
                 --disable-nls
                 --disable-werror
    - make: ~
    - preinstall: case $(uname -m) in
                    x86_64) mkdir -pv $PREFIX/lib && ln -svf lib $PREFIX/lib64 ;;
                  esac
    - install: ~
pass2:
    - configure:
        vars: CC=$LFS_TGT-gcc
              AR=$LFS_TGT-ar
              RANLIB=$LFS_TGT-ranlib
        params: --prefix=$PREFIX
                --disable-nls
                --with-lib-path=$PREFIX/lib
                --with-sysroot
    - make: ~
    - install: ~
    - postinstall: make -C ld clean;
                   make -C ld LIB_PATH=/usr/lib:/lib;
                   cp -v ld/ld-new $PREFIX/bin;
build:
    - test-pty: |
             expect -c "spawn ls" 2> spawn-got.txt
             touch spawn-expected.txt
             diff spawn-expected.txt spawn-got.txt
             rm spawn-expected.txt spawn-got.txt
    - supress-info:
        command: |
                 rm -fv etc/standards.info;
                 sed -i.bak '/^INFO/s/standards.info //' etc/Makefile.in;
        dir: src
    - configure: --prefix=$PREFIX
                 --enable-shared
    - make: tooldir=$PREFIX
    - check: ~
    - install:
        command: make tooldir=$PREFIX install
cross-build:
    - configure: --prefix=$PREFIX
                 --target=$TARGET
                 --infodir=`pwd`/info-tmp
                 --localedir=`pwd`/locale-tmp
    - make: ~
    - install: ~
