name: bzip2
download: 
 - link: http://www.bzip.org/downloads.html
chapter5:
 - make:
     dir: src
 - inst: 
     command: make PREFIX=$PREFIX install
     dir: src
build:
 - preconfigure:
    command: |
             sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile;
             sed -i "s@(PREFIX)/man@(PREFIX)/share/man@g" Makefile;
    dir: src
 - make-so:
    command:
        make -f Makefile-libbz2_so;
        make clean;
    dir: src
 - make:
    dir: src
 - inst:
     command: make PREFIX=$PREFIX install
     dir: src
 - postinstall:
     command:
         cp -v bzip2-shared /bin/bzip2;
         cp -av libbz2.so* /lib;
         ln -sv ../../lib/libbz2.so.1.0 /usr/lib/libbz2.so;
         rm -v /usr/bin/{bunzip2,bzcat,bzip2};
         ln -sv bzip2 /bin/bunzip2;
         ln -sv bzip2 /bin/bzcat;
     dir: src
