name: cmake
description: A modern toolset used for generating Makefiles
requires: curl,libarchive,expat
download:
    - link: http://www.cmake.org/files/
      method: wget-folder
      wget-folder-name: 'v'
build:
    - configure: --prefix=$PREFIX
                 --mandir=/share/man
                 --docdir=/share/doc/cmake$PACKAGE_VERSION
    - make: ~
    - install: ~
    - postinstall: mkdir -p $PREFIX/lib/cmake;
root-after:
    - cmake-lib: lupm-dir.sh $PREFIX/lib/cmake;
