name: cmus
description: Console MUSic player
requires: libmad,ffmpeg,pulseaudio
download:
    - method: sourceforge
      versionPattern: -v[0-9.]\\+
build:
    - configure:
        dir: src
        params: prefix=$PREFIX
    - make:
        dir: src
    - install:
        dir: src
