name: connman
requires: iptables,gnutls
installgroups: install,dbusinstall,systemdinstall
download:
 - link: http://www.kernel.org/pub/linux/network/connman/
build:
 - configure: --prefix=$PREFIX
              --sysconfdir=/etc
              --localstatedir=/var
 - make: ~
 - check: ~
 - test: ~
 - install: ~
 - postinstall: install -m755 client/connmanctl /usr/bin
