name: coreutils
download:
 - link: http://ftp.gnu.org/gnu/coreutils/
pass1:
 - configure: --prefix=$PREFIX --enable-install-program=hostname
 - make: ~
 - tst: make RUN_EXPENSIVE_TESTS=yes check
 - install: ~
