name: coreutils
description: Old coreutils with su executable for usage prior to shadow
download:
    - link: http://ftp.gnu.org/gnu/coreutils/coreutils-8.17.tar.xz
      method: fixed
build:
    - configure: --prefix=$PREFIX
    - make: ~
    - inst: cp -v src/su $PREFIX/bin
