name: diffutils
download:
 - link: http://ftp.gnu.org/gnu/diffutils/
chapter5:
 - configure: --prefix=$PREFIX
 - make: ~
 - check: ~
 - install: ~
build:
 - preconfigure: sed -i 's:= @mkdir_p@:= /bin/mkdir -p:' po/Makefile.in.in
 - configure: --prefix=$PREFIX
 - make: ~
 - check: ~
 - install: ~
