name: DirectFB
packagename: directfb
requires: flux
download:
 - link: http://www.directfb.org/index.php?path=Main%2FDownloads
build:
 - configure: --prefix=$PREFIX
 - make: ~
 - check: ~
 - install: ~
