name: freeglut
description: Compatible, completely opensourced clone of the GLUT library
installgroups: install,xorginstall
requires: mesalib,glu
download:
    - method: sourceforge
build:
    - configure: --prefix=$PREFIX
                 --disable-static
    - make: ~
    - install: ~
