name: gawk
download:
 - link: http://ftp.gnu.org/gnu/gawk/
chapter5:
 - configure: --prefix=$PREFIX
 - make: ~
 - check: ~
 - install: ~
build:
 - configure: --prefix=$PREFIX  --libexecdir=$PREFIX/lib
 - make: ~
 - check: ~
 - install: ~
