name: gcc
description: GNU Compiler Collection with newlib
installgroups: install,tty
download:
    - link: http://ftp.gnu.org/gnu/gcc/
      method: wget-folder
    - name: newlib
      link: ftp://sourceware.org/pub/newlib/
cross-build:
    - preconfigure: ln -svf $NEWLIB_SRC_DIR/newlib;
                    ln -svf $NEWLIB_SRC_DIR/libgloss;
    - configure: --prefix=$PREFIX
                 --target=$TARGET
                 --enable-languages=c,c++
                 --libexecdir=$PREFIX/lib
                 --with-newlib
                 --with-headers=$NEWLIB_SRC_DIR/newlib/libc/include
    - make: ~
    - install: ~
