name: gettext
download:
 - link: http://ftp.gnu.org/gnu/gettext/
chapter5:
 - configure:
     command: EMACS="no" $PACKAGE_SRCDIR/gettext-tools/configure --prefix=$PREFIX --disable-shared
 - gnulib: make -C gnulib-lib
 - msgfmt: make -C src msgfmt
 - msgmerge: make -C src msgmerge
 - xgettext: make -C src xgettext
 - cinstall: cp -v src/{msgfmt,msgmerge,xgettext} $PREFIX/bin
build:
 - configure: --prefix=$PREFIX
              --docdir=/usr/share/doc/gettext$PACKAGE_VERSION
 - make: ~
 - check: ~
 - install: ~
