name: git
installgroups: install,perlmod
requirements: curl,expat,openssl,python,pcre,svn,asciidoc,xmlto
download:
    - link: https://www.kernel.org/pub/software/scm/git/
build:
   - autoconf:
        command: autoconf
        dir: src
   - configure:
        params: --prefix=$PREFIX
                --libexecdir=$PREFIX/lib
                --with-gitconfig=/etc/gitconfig
        dir: src
   - make:
        dir: src
        command: make NO_GETTEXT=1
#   - test:
#        dir: src
#        command: make NO_GETTEXT=1 test
   - install:
        dir: src
        command: make NO_GETTEXT=1 install
   - install-man: wget -c https://www.kernel.org/pub/software/scm/git/git-manpages$PACKAGE_VERSION.tar.xz;
                  tar -xf git-manpages$PACKAGE_VERSION.tar.xz -C /usr/share/man --no-overwrite-dir;
