name: glew
description: The OpenGL Extension Wrangler Library (GLEW) is a cross-platform open-source C, C++ extension loading library
installgroups: install,xorginstall
requires: mesalib
envvars: GLEWDEST=$PREFIX
download:
    - method: sourceforge
      versionPattern: -[0-9]\\+\\.[0-9.]\\+
build:
    - make:
        dir: src
    - install:
        dir: src
