name: gperf
download:
 - link: http://ftp.gnu.org/gnu/gperf/
build:
 - configure: --prefix=$PREFIX
              --docdir=/usr/share/doc/gperf$PACKAGE_VERSION
 - make: ~
 - check:
    vars: MAKEFLAGS=""
 - install: ~
