name: grep
download:
 - link: http://ftp.gnu.org/gnu/grep/
chapter5:
 - configure: --prefix=$PREFIX
 - make: ~
 - check: ~
 - install: ~
build:
 - configure: --prefix=$PREFIX --bindir=/bin
 - make: ~
 - check: ~
 - install: ~
