name: grub
download:
 - link: http://ftp.gnu.org/gnu/grub/
build:
 - preconfigure: sed -i -e '/gets is a/d' grub-core/gnulib/stdio.in.h
 - configure: --prefix=$PREFIX
              --sysconfdir=/etc
              --disable-grub-emu-usb
              --disable-efiemu
              --disable-werror
 - make: ~
 - install: ~
