name: gsettings-desktop-schemas
description: Contains a collection of GSettings schemas for settings
             shared by various components of a GNOME Desktop
requires: glib,intltool,gobject-introspection
download:
    - link: http://ftp.gnome.org/pub/gnome/sources/gsettings-desktop-schemas/
      method: wget-folder
      wget-folder-name: ''
build:
    - configure: --prefix=$PREFIX
                 --disable-static
    - make: ~
    - install: ~
