name: gst-plugins-base
installgroups: install,gstplugininstall
description: A well-groomed and well-maintained collection of GStreamer plug-ins and elements
requires: gstreamer,libxml2
download:
    - link: http://gstreamer.freedesktop.org/src/gst-plugins-base/
build:
    - configure: --prefix=$PREFIX
    - make: ~
    - check: ~
    - install: ~
