name: icu4c
requires: 
description: A library for laying out and rendering of text, 
             with an emphasis on internationalization
download:
    - link: http://download.icu-project.org/files/icu4c/
      method: wget-folder
      wget-folder-name: ''
      suffix: '-src'
      versionPattern: -[0-9_]\\+
build:
    - move: if [ -e ~/source/icu ]; then
                mv ~/source/icu $PACKAGE_SRCDIR;
            fi;
    - configure:
        command: $PACKAGE_SRCDIR/source/configure
        params: --prefix=$PREFIX
    - make: ~
    - check: ~
    - install: ~
