name: inetutils
download:
 - link: http://ftp.gnu.org/gnu/inetutils/
build:
 - preconfigure: echo '#define PATH_PROCNET_DEV "/proc/net/dev"' >> ifconfig/system/linux.h
 - configure: --prefix=$PREFIX
              --libexecdir=/usr/sbin
              --localstatedir=/var
              --disable-logger
              --disable-syslogd
              --disable-whois
              --disable-servers
 - make: ~
 - check: ~
 - install: ~
 - postinstall: mv -v /usr/bin/{hostname,ping,ping6,traceroute} /bin;
                mv -v /usr/bin/ifconfig /sbin;
