name: libatomic_ops
download:
 - link: http://www.hpl.hp.com/research/linux/atomic_ops/download.php4
build:
#"command">sed -i 's#AM_CONFIG_HEADER#AC_CONFIG_HEADERS#' configure.ac &amp;&amp;
#sed -i 's#AC_PROG_RANLIB#AC_LIBTOOL_DLOPEN\nAC_PROG_LIBTOOL#' configure.ac &amp;&amp;
#sed -i 's#b_L#b_LTL#;s#\.a#.la#g;s#_a_#_la_#' src/Makefile.am &amp;&amp;
#sed -i 's#\.a#.so#g;s#\.\./src/#../src/.libs/#g' tests/Makefile.am &amp;&amp;
#sed -i 's#pkgdata#doc#' doc/Makefile.am &amp;&amp;
#autoreconf -fi &amp;&amp;
 - configure: --prefix=$PREFIX
              --docdir=/usr/share/doc/libatomic_ops$PACKAGE_VERSION
              --disable-static
 - make: ~
 - check: ~
 - install: ~
