name: libsecret
description: Contains a GObject based library for accessing the Secret Service API
requires: glib,libgcrypt
download:
    - link: http://ftp.gnome.org/pub/gnome/sources/libsecret/
      method: wget-folder
      wget-folder-name: ''
build:
    - configure: --prefix=$PREFIX
                 --disable-static
                 --disable-manpages
    - make: ~
    # TODO: check if we are from X terminal, then make check
    - install: ~
