name: libsndfile
download:
 - link: http://www.mega-nerd.com/libsndfile/files/
build:
 - configure: --prefix=$PREFIX
              --disable-static
 - make: ~
 - check: ~
 - install:
    command: make htmldocdir=$PREFIX/share/doc/libsndfile$PACKAGE_VERSION install
