name: ncurses
download:
 - link: ftp://ftp.gnu.org/gnu/ncurses/
chapter5:
 - configure: --prefix=$PREFIX
              --with-shared
              --without-debug
              --without-ada
              --enable-overwrite
 - make: ~
 - install: ~
build:
 - configure: --prefix=$PREFIX
              --mandir=$PREFIX/share/man
              --with-shared
              --without-debug
              --enable-pc-files
              --enable-widec
 - make: ~
 - install: ~
 - postinstall:
     mv -v /usr/lib/libncursesw.so.5* /lib;
     ln -sfv ../../lib/$(readlink /usr/lib/libncursesw.so) /usr/lib/libncursesw.so;
     for lib in ncurses form panel menu ; do
        rm -vf                    /usr/lib/lib${lib}.so;
        echo "INPUT(-l${lib}w)" > /usr/lib/lib${lib}.so;
        ln -sfv lib${lib}w.a      /usr/lib/lib${lib}.a;
        ln -sfv ${lib}w.pc        /usr/lib/pkgconfig/${lib}.pc;
     done;
 - nonwide-lib:
     ln -sfv libncurses++w.a /usr/lib/libncurses++.a;
     rm -vf                     /usr/lib/libcursesw.so;
     echo "INPUT(-lncursesw)" > /usr/lib/libcursesw.so;
     ln -sfv libncurses.so      /usr/lib/libcurses.so;
     ln -sfv libncursesw.a      /usr/lib/libcursesw.a;
     ln -sfv libncurses.a       /usr/lib/libcurses.a;
 - install-doc:
     command:
        mkdir -pv       /usr/share/doc/ncurses$PACKAGE_VERSION;
        cp -v -R doc/* /usr/share/doc/ncurses$PACKAGE_VERSION;
     dir: src
