name: openscad
requires: qt,cgal,eigen,opencsg
description: Language to model 3d objects
download:
    - link: http://files.openscad.org/
      suffix: .src
build:
    - preconfigure: sed -i "s#/usr/local#$PREFIX#g" openscad.pro;
    - qmake: qmake $PACKAGE_SRCDIR;
    - make: ~
    - install: ~
