name: pciutils
download:
 - link: http://www.kernel.org/pub/software/utils/pciutils/
build:
 - make:
    command: make PREFIX=$PREFIX
                  SHAREDIR=$PREFIX/share/misc
                  MANDIR=$PREFIX/share/man
                  SHARED=yes
                  ZLIB=no
                  all
    dir: src
 - install:
    command: make PREFIX=$PREFIX
                  SHAREDIR=$PREFIX/share/misc
                  MANDIR=$PREFIX/share/man
                  SHARED=yes
                  ZLIB=no
                  install install-lib
    dir: src
 - mode:
    command: chmod -v 755 $PREFIX/lib/libpci.so.*
