name: YAML-LibYAML
packagename: perlmod-libyaml
installgroups: perlmod,install
download:
 - link: http://search.cpan.org/~ingy/YAML-LibYAML-0.41/lib/YAML/XS.pm
build:
 - config:
    dir: src
    command: perl Makefile.PL
 - make:
    dir: src
 - install:
    dir: src
