name: XML-Parser
packagename: perlmod-xml-parser
installgroups: perlmod,install
download:
 - link: http://search.cpan.org/CPAN/authors/id/T/TO/TODDR/
build:
 - config:
    dir: src
    command: perl Makefile.PL
 - make:
    dir: src
 - install:
    dir: src
