name: pkg-config
download:
 - link: http://pkgconfig.freedesktop.org/releases/
build:
 - configure: --prefix=$PREFIX
              --with-internal-glib
              --disable-host-tool
              --docdir=/usr/share/doc/pkg-config$PACKAGE_VERSION
 - make: ~
 - check: ~
 - install: ~
