name: Python
packagename: python-2
requirements: expat,libffi
download:
   - link: http://www.python.org/download/
     versionPattern: -2[0-9.]\\+
#2to3 is installed by python3
root-before:
   - 2to3: if [ -f /usr/bin/2to3 ]; then
               mv -v /usr/bin/2to3{,-backup};
           fi
build:
   - configure:
      params: --prefix=$PREFIX
              --enable-shared
              --with-system-expat
              --with-system-ffi
              --enable-unicode=ucs4
      dir: src
   - make:
      dir: src
   #- test:
      #dir: src
   - install:
      dir: src
   - postinstall:
      command: chmod -v 755 /usr/lib/libpython${PACKAGE_VERSION:1:3}.so.*;
      dir: src
   - install-doc: wget -c http://docs.python.org/ftp/python/doc/${PACKAGE_VERSION:1}/python${PACKAGE_VERSION}-docs-html.tar.bz2;
                  install -v -dm755 /usr/share/doc/python$PACKAGE_VERSION;
                  tar --strip-components=1 -C /usr/share/doc/python$PACKAGE_VERSION
                                           -xvf python$PACKAGE_VERSION-docs-html.tar.bz2;
                  find /usr/share/doc/python$PACKAGE_VERSION -type d -exec chmod 0755 {} \; ;
                  find /usr/share/doc/python$PACKAGE_VERSION -type f -exec chmod 0644 {} \; ;
#2to3 is installed by python3
root-after:
   - 2to3: rm -f /usr/bin/2to3;
           if [ -f /usr/bin/2to3-backup ]; then
               mv /usr/bin/2to3{-backup,};
           fi
   - pythonmod: groupadd -f pythonmodinstall;
                lupm-dir.sh /usr/lib/python${PACKAGE_VERSION:1:3}/site-packages/ pythonmodinstall;
