name: ruby
description: Ruby language
download:
    - link: ftp://ftp.ruby-lang.org/pub/ruby/
build:
    - configure: --prefix=$PREFIX
                 --docdir=/usr/share/doc/ruby$PACKAGE_VERSION
                 --enable-shared
    - make: ~
    - test: ~
    - install: ~
root-after:
   - ruby-gems: groupadd -f rubygemsinstall;
                lupm-dir.sh /usr/lib/ruby/gems/${PACKAGE_VERSION:1:3}.0 rubygemsinstall;
                lupm-dir.sh /usr/lib/ruby/gems/${PACKAGE_VERSION:1:3}.0/cache rubygemsinstall;
                lupm-dir.sh /usr/lib/ruby/gems/${PACKAGE_VERSION:1:3}.0/doc rubygemsinstall;
                lupm-dir.sh /usr/lib/ruby/gems/${PACKAGE_VERSION:1:3}.0/specifications rubygemsinstall;
                lupm-dir.sh /usr/lib/ruby/gems/${PACKAGE_VERSION:1:3}.0/gems rubygemsinstall;
