name: SDL
description: The Simple DirectMedia Layer is a cross-platform library designed
             to make it easy to write multimedia software, such as games
             and emulators
download:
    - link: http://www.libsdl.org/release/
build:
    - preconfigure: |
                    if [ "x$PACKAGE_VERSION" == "x-1.2.15" ]; then
                        sed -i '/_XData32/s:register long:register _Xconst long:' src/video/x11/SDL_x11sym.h;
                    fi;
    - configure: --prefix=$PREFIX
                 --disable-static
    - make: ~
    - install: ~
    - install-doc: install -v -m755 -d $PREFIX/share/doc/SDL$PACKAGE_VERSION/html;
                   install -v -m644    $PACKAGE_SRCDIR/docs/html/*.html
                                       $PREFIX/share/doc/SDL$PACKAGE_VERSION/html;

