name: sshfs-fuse
installgroups: install
download:
    - method: sourceforge
      sourceforge-name: fuse
build:
    - configure: --prefix=$PREFIX
                 --disable-static
    - make: ~
    - install: ~
