name: st
description: Simple Terminal
download:
    - link: http://st.suckless.org/
build:
    - preconfigure: sed -i "s@/usr/local@$PREFIX@" config.mk
    - make:
        dir: src
    - install:
        dir: src
root-after:
    - terminfo: mv -v /usr/src/st/.terminfo/s/* $PREFIX/share/terminfo/s/
