name: tzdata
download: 
   - link: http://www.iana.org/time-zones
     suffix: i
build:
 - extract: tar -xvf $TZDATA_SRC_ARCHIVE
 - timezone: |
             ZONEINFO=$PREFIX/share/zoneinfo;
             mkdir -pv $ZONEINFO/{posix,right};
             for tz in etcetera southamerica northamerica europe africa antarctica  \
                 asia australasia backward pacificnew systemv; do
                     zic -L /dev/null   -d $ZONEINFO       -y "sh yearistype.sh" ${tz};
                     zic -L /dev/null   -d $ZONEINFO/posix -y "sh yearistype.sh" ${tz};
                     zic -L leapseconds -d $ZONEINFO/right -y "sh yearistype.sh" ${tz};
             done;
             cp -v zone.tab iso3166.tab $ZONEINFO;
             zic -d $ZONEINFO -p America/New_York;
             unset ZONEINFO;
 - tzselect: tzselect
 - localtime: |
              TZ=`grep "export TZ" ../build-logs/tzselect.log | sed "s/.*TZ='\([^']\+\)'.*/\1/"`
              cp -v --remove-destination /usr/share/zoneinfo/$TZ /etc/localtime
