name: unzip
download:
 - method: sourceforge
   sourceforge-name: infozip
   sortmethod: ''
build:
    - make:
        command: |
                 case `uname -m` in
                   i?86)
                     sed -i -e 's/DASM"/DASM -DNO_LCHMOD"/' unix/Makefile;
                     make -f unix/Makefile linux;
                     ;;
                   *)
                     sed -i -e 's/CFLAGS="-O -Wall/& -DNO_LCHMOD/' unix/Makefile;
                     make -f unix/Makefile linux_noasm;
                     ;;
                 esac;
        dir: src
    - check:
        dir: src
    - install:
        dir: src
        command: make prefix=$PREFIX install
