name: wget
download:
 - link: http://ftp.gnu.org/gnu/wget/
chapter5:
 - configure: --prefix=$PREFIX --with-ssl=openssl
 - make: ~
 - install: ~
build:
 - configure: --prefix=$PREFIX --with-ssl=openssl --sysconfdir=/etc
 - make: ~
 - install: ~
