name: wxWidgets
description: A C++ library that lets developers create applications for Windows, Mac OS X, Linux and other platforms with a single code base
requires: gtk
download:
    - link: http://www.wxwidgets.org/downloads/
build:
    - configure: --prefix=$PREFIX
                 --disable-static
    # disable non-english messages
    - disable-langs: sed -i 's/^LOCALE_LINGUAS =.*$/LOCALE_LINUAS =/' Makefile;
                     sed -i 's/^LOCALE_MSW_LINGUAS =.*$/LOCALE_MSW_LINUAS =/' Makefile;
    - make: ~
    - install: ~
