name: presentproto
installgroups: install,xorginstall
description: Xorg protocol header part
download:
    - link: ftp://ftp.x.org/pub/individual/proto/
build:
    - configure: --prefix=$PREFIX
    - install: ~
