name: xf86-input-synaptics
installgroups: install,xorginstall
requires: mtdev
description: Contains the X.Org Input Driver, support programs
             and SDK for Synaptics touchpads
download:
    - link: ftp://ftp.x.org/pub/individual/driver/
build:
    - configure: --prefix=$PREFIX
                 --disable-static
    - make: ~
    - install: ~
