name: libXdmcp
installgroups: install,xorginstall
description: A library implementing the X Display Manager Control Protocol
download:
    - link: ftp://ftp.x.org/pub/individual/lib/
build:
    - configure: --prefix=$PREFIX
                 --disable-static
    - make: ~
    - install: ~
