#!/bin/sh

export EDITOR=vim
alias ls="ls --color"
alias grep="grep --color"

case "color" in
    *color*)
        case "$UID" in
        0)
            usercolor="\[\033[01;31m\]";
            symbol="#"
            ;;
        1094)
            usercolor="\[\033[01;32m\]";
            symbol="$"
            ;;
        *)
            usercolor="\[\033[01;33m\]";
            symbol=">"
            ;;
        esac

        dircolor="\[\033[01;34m\]";
        normal="\[\033[00m\]";
        ;;
    *)
        usercolor="";
        dircolor="";
        normal="";
        ;;
esac;

PS1="$usercolor\u$normal$dircolor\w$normal$usercolor$symbol$normal ";
